WebApp/ViewComponents/NavBarViewComponent.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.ViewComponents;

public class NavBarViewComponent(UserManager<User> userManager) : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var NavBarItems = new List<NavBarItem>();

        var userIdentity = UserClaimsPrincipal.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await userManager.FindByIdAsync(userIdentity ?? "");
        var roles = Enum.GetValues<Role>();
        var userRole = await userManager.GetRolesAsync(user ?? new User());
        var roleLevels = userRole
            .Select(Enum.Parse<Role>)
            .Select(r => (int)r)
            .ToList();
        var maxRoleLevel = roleLevels.Count == 0 ? -1 : roleLevels.Max();
        Role? role;
        if (maxRoleLevel == -1)
            role = null;
        else
            role = roles.FirstOrDefault(r => (int)r == maxRoleLevel);

        BuildNavBarItems(NavBarItems, role);
        return View(NavBarItems);
    }

    private void BuildNavBarItems(List<NavBarItem> NavBarItems, Role? role)
    {
        NavBarItems.Add("Home", "Home", "Index");
        switch (role)
        {
            case Role.Manager:
                BuildManagerItems(NavBarItems);
                break;
            case Role.Teacher:
                BuildTeacherItems(NavBarItems);
                break;
            case Role.Student:
                BuildStudentItems(NavBarItems);
                break;
        }
    }

    private static void BuildManagerItems(List<NavBarItem> NavBarItems)
    {
        NavBarItems.Add("Courses", "Courses", "Index");
        NavBarItems.Add("Teachers", "Teachers", "Index");
        NavBarItems.Add("Students", "Students", "Index");
    }

    private static void BuildTeacherItems(List<NavBarItem> NavBarItems)
    {
        NavBarItems.Add("Courses", "Courses", "Index");
    }

    private static void BuildStudentItems(List<NavBarItem> NavBarItems)
    {
        NavBarItems.Add("Courses", "Students", "View");
    }

    public struct NavBarItem
    {
        public static NavBarItem Create(string name, string controller, string action)
        {
            return Create(name, "", controller, action);
        }

        public static NavBarItem Create(string name, string area, string controller, string action)
        {
            return new NavBarItem { Name = name, Area = area, Controller = controller, Action = action };
        }

        public string Name { get; init; }
        public string Area { get; init; }
        public string Controller { get; init; }
        public string Action { get; init; }
    }
}

internal static class Extensions
{
    public static void Add(
        this List<NavBarViewComponent.NavBarItem> list,
        string name,
        string controller,
        string action
    )
    {
        list.Add(NavBarViewComponent.NavBarItem.Create(name, "", controller, action));
    }

    public static void Add(
        this List<NavBarViewComponent.NavBarItem> list,
        string name,
        string area,
        string controller,
        string action
    )
    {
        list.Add(NavBarViewComponent.NavBarItem.Create(name, area, controller, action));
    }
}

WebApp/Views/Shared/_CourseCard.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@using WebApp.Core
@using WebApp.Data
@model Course
@inject IAuthorizationService auth
@inject ApplicationIdentityDbContext ctx
@inject UserManager<User> UserManager

@{
    var manageCourse = await auth.AuthorizeAsync(User, null, Policies.CanManageCourses);
    var assignStudent = await auth.AuthorizeAsync(User, null, Policies.CanAssignStudents);
    var user = await UserManager.GetUserAsync(User);
    ViewBag.HasManageCourse = manageCourse.Succeeded;
    ViewBag.HasAssignStudent = assignStudent.Succeeded;
    ViewBag.CanAssignThisCourse = Model.TeacherId == user?.Id;
    var detailsUrl = Url.Action("Details", "Courses", new { id = Model.CourseId });
}

<div id="card-@Model.CourseId" class="card course-card" style="cursor: pointer" data-details-url="@detailsUrl">
    <div class="card-body d-inline-flex">
        <div class="flex-grow-1">
            <h5 class="card-title">@Model.CourseName (@Model.CourseCode)</h5>
            <p class="card-text">@(Model.Description ?? "<No description>")</p>
            <p class="card-text">Assigned to: @(Model.Teacher?.FullName ?? "<no teacher>")</p>
            <p class="card-text">Enrolled students: @Model.AssignedUsers.Count()</p>
            <div class="row mt-3">
                <p class="col card-text me-1">From: @Model.StartDate.ToString("dd/MM/yyyy")</p>
                <p class="col card-text me-1">To: @Model.EndDate.ToString("dd/MM/yyyy")</p>
            </div>
        </div>
        <div class="d-flex flex-column">
            @if (ViewBag.HasAssignStudent)
            {
                @if (ViewBag.CanAssignThisCourse || ViewBag.HasManageCourse)
                {
                    <a class="btn btn-primary m-1" asp-area=""
                       asp-controller="Enrollments"
                       asp-action="Enroll"
                       asp-route-courseId="@Model.CourseId"
                       asp-route-returnUrl="@Context.Request.Path">
                        Enroll
                    </a>
                }
                else
                {
                    <a class="btn btn-primary m-1 disabled" asp-area="">
                        Enroll
                    </a>
                }
            }
            @if (ViewBag.HasManageCourse)
            {
                <a class="btn btn-primary m-1" asp-area=""
                   asp-controller="Courses"
                   asp-action="Edit"
                   asp-route-id="@Model.CourseId">
                    Edit
                </a>
                <button class="btn btn-danger m-1"
                        data-bs-toggle="modal"
                        data-bs-target="#deleteCourseModal"
                        data-id="@Model.CourseId">
                    Delete
                </button>
            }
        </div>
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    var welcome = "Hello";
    var user = await UserManager.GetUserAsync(User);
    var name = user?.FullName;
    var birthDate = user?.BirthDate ?? default;

    if (!string.IsNullOrEmpty(name))
    {
        if (DateTime.Now.Month == birthDate.Month && DateTime.Now.Day == birthDate.Day)
        {
            welcome = "Happy Birthday 🎂";
        }
    }
    else
    {
        name = "<unknown>";
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body class="bg-light text-dark d-flex flex-column min-vh-100 m-0">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @await Component.InvokeAsync("NavBar")
                </ul>

                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index"
                               title="Manage">@welcome, @name</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                                  asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-danger text-light">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container flex-grow-1">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<footer class="border-top footer text-muted">
    <div class="container d-flex">
        <div class="flex-grow-1 d-inline-flex">
            <p class="m-1 flex-grow-1">&copy; 2025 - Student Management System </p>
            <p class="m-1">
                <strong>
                    @DateTime.Now.ToString("dd/MM/yyyy")
                </strong>
            </p>
        </div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/htmx/htmx.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

WebApp/Views/Shared/_StudentCard.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@using WebApp.Core
@model User
@inject IAuthorizationService auth
@inject UserManager<User> UserManager

@{
    ViewBag.IsStudent = await UserManager.IsInRoleAsync(Model, nameof(Role.Student));
    ViewBag.CanManage = (await auth.AuthorizeAsync(User, Policies.CanManageStudents)).Succeeded;
}



<div class="card mb-3">
    <div class="card-body d-flex align-items-center">
        <div
            class="mr-3 d-inline-flex flex-column flex-grow-1 align-items-start justify-content-start rounded-circle">
            @if (ViewBag.IsStudent)
            {
                <h5 class="card-title">@Model.FullName - @Model.StudentCode</h5>
                <p class="mt-1 mb-0">@Model.UserName</p>
                <p class="mt-1 mb-0">@Model.PhoneNumber</p>
            }
        </div>
        @if (ViewBag.CanManage)
        {
            <div class="d-inline-flex flex-column">
                <a class="btn btn-primary m-1" asp-controller="Students" asp-action="Edit"
                   asp-route-id="@Model.Id">
                    Edit
                </a>
                <button class="btn btn-danger m-1"
                        data-bs-toggle="modal"
                        data-bs-target="#deleteStudentModal"
                        data-id="@Model.Id">
                    Delete
                </button>
            </div>
        }
    </div>
</div>

<script>
</script>

WebApp/Views/Shared/_TeacherCard.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@using WebApp.Core
@model User
@inject IAuthorizationService auth
@inject UserManager<User> UserManager

@{
    ViewBag.IsTeacher = await UserManager.IsInRoleAsync(Model, nameof(Role.Teacher));
    ViewBag.CanManage = (await auth.AuthorizeAsync(User, Policies.CanAssignTeachers)).Succeeded;
}



<div class="card mb-3">
    <div class="card-body d-flex align-items-center">
        <div
            class="mr-3 d-inline-flex flex-column flex-grow-1 align-items-start justify-content-start rounded-circle">
            @if (ViewBag.IsTeacher)
            {
                <h5 class="card-title">@Model.FullName</h5>
                <p class="mt-1 mb-0">@Model.UserName</p>
                <p class="mt-1 mb-0">@Model.PhoneNumber</p>
            }
        </div>
        @if (ViewBag.CanManage)
        {
            <div class="d-inline-flex flex-column">
                <a class="btn btn-primary m-1" asp-controller="Teachers" asp-action="Edit"
                   asp-route-id="@Model.Id">
                    Edit
                </a>
                <button class="btn btn-danger m-1"
                        data-bs-toggle="modal"
                        data-bs-target="#deleteTeacherModal"
                        data-id="@Model.Id">
                    Delete
                </button>
            </div>
        }
    </div>
</div>

<script>
</script>